blob:
  container: "jackson"
  prefix: "js_exp"
local:
  root: "/mnt/data/js"

exp_root: "exp/v1"   # 只在这里写一次版本

paths:
  raw:        "raw"
  clean:      "clean" # in exp_root
  clean_shards: "clean_shards" # in exp_root 用来存放清洗后的分片数据，为后续特征工程做准备
  fe_shards:  "fe_shards" # in exp_root
  sample_fe: "sample_fe" # in exp_root
  panel_shards: "panel_shards" # in exp_root
  models:     "models" # in exp_root
  reports:    "reports" # in exp_root
  # 本地专用
  sample_mm: "sample_mm" # in local root
  panel_mm:  "panel_mm"  # in local root
  mm:         "mm"
  cache:      "cache"
  tmp:        "tmp"

# 关键列与时间范围
keys: ["symbol_id","date_id","time_id"]
target: "responder_6"
weight: "weight"

# 时间特征列参数

close_auction_ticks: 5
ticks: 968
bucket_size: 6
white_list: ["time_pos", "time_sin", "time_cos", "time_bucket_6", "is_open_auction", "is_close_auction"] # NB: 6 here must match bucket_size

date_lo: 1190
date_hi: 1429
embargo_days: 5

test_lo: 1530