device_type: gpu
gpu_device_id: 0
learning_rate: 0.03
num_leaves: 63
min_data_in_leaf: 300
feature_fraction: 0.6
feature_fraction_bynode: 0.8
bagging_fraction: 0.7
bagging_freq: 1
lambda_l2: 3.0
max_bin: 31
bin_construct_sample_cnt: 50000
min_data_in_bin: 5
num_threads: 8
seed: 42
first_metric_only: true
deterministic: true
